"""Closed vocabularies used at deterministic boundaries."""

from enum import StrEnum


class RequirementKind(StrEnum):
    FUNCTIONAL = "FUNCTIONAL"
    NON_FUNCTIONAL = "NON_FUNCTIONAL"
    BUSINESS_RULE = "BUSINESS_RULE"
    USER_STORY = "USER_STORY"


class IssueType(StrEnum):
    AMBIGUOUS_TERM = "AMBIGUOUS_TERM"
    UNTESTABLE = "UNTESTABLE"
    INCOMPLETE = "INCOMPLETE"
    DUPLICATE = "DUPLICATE"
    CONTRADICTION = "CONTRADICTION"
    NON_ATOMIC = "NON_ATOMIC"
    MISSING_ACCEPTANCE_CRITERIA = "MISSING_ACCEPTANCE_CRITERIA"
    UNDEFINED_TERM = "UNDEFINED_TERM"


class Severity(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class FindingStatus(StrEnum):
    CANDIDATE = "CANDIDATE"
    VERIFIED = "VERIFIED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"


class EvidenceVerdict(StrEnum):
    RESOLVED = "RESOLVED"
    SOURCE_UNKNOWN = "SOURCE_UNKNOWN"
    SOURCE_CHANGED = "SOURCE_CHANGED"
    QUOTE_NOT_FOUND = "QUOTE_NOT_FOUND"
    QUOTE_AMBIGUOUS = "QUOTE_AMBIGUOUS"


class WorkflowStatus(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATED = "VALIDATED"
    ANALYZING = "ANALYZING"
    VERIFYING = "VERIFYING"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"
    ERROR = "ERROR"
    EXPORTED = "EXPORTED"


class ApprovalAction(StrEnum):
    APPROVE = "APPROVE"
    EDIT = "EDIT"
    REJECT = "REJECT"
    REQUEST_REVISION = "REQUEST_REVISION"


class AnalysisOrigin(StrEnum):
    FIXTURE = "FIXTURE"
    RULE = "RULE"
    OPENAI = "OPENAI"


class Responsibility(StrEnum):
    MODEL = "MODEL"
    DETERMINISTIC = "DETERMINISTIC"
    HUMAN = "HUMAN"
